apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    version: v1
  name: nginx-svc
  namespace: guestbook
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP

